/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.*;
import Modelo.*;
import Vista.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author dylan
 */
public class VistaAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdmin.class.getName());
    private final Usuario logueado;
    private int idUsuarioSeleccionado;
    private int idActivoSeleccionado;
    private int idIncidenteSeleccionado;

    public int getIdActivoSeleccionado() {
        return idActivoSeleccionado;
    }

    public Usuario getLogueado() {
        return logueado;
    }

    public void setIdActivoSeleccionado(int idActivoSeleccionado) {
        this.idActivoSeleccionado = idActivoSeleccionado;
    }

    public int getIdIncidenteSeleccionado() {
        return idIncidenteSeleccionado;
    }

    public void setIdIncidenteSeleccionado(int idIncidenteSeleccionado) {
        this.idIncidenteSeleccionado = idIncidenteSeleccionado;
    }

    public int getIdUsuarioSeleccionado() {
        return idUsuarioSeleccionado;
    }

    public void setIdUsuarioSeleccionado(int idUsuarioSeleccionado) {
        this.idUsuarioSeleccionado = idUsuarioSeleccionado;
    }

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin(Usuario logueado) {
        initComponents();
        this.logueado = logueado;
    }

    public JLabel getLblBusquedaIncidente() {
        return lblBusquedaIncidente;
    }

    public JTextField getTxtBusquedaIncidente() {
        return txtBusquedaIncidente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblNombreUsuario = new javax.swing.JLabel();
        lblUsuarioNombre = new javax.swing.JLabel();
        txtUsuarioNombre = new javax.swing.JTextField();
        lblUsuarioApellido1 = new javax.swing.JLabel();
        txtUsuarioApellido1 = new javax.swing.JTextField();
        lblUsuarioApellido2 = new javax.swing.JLabel();
        txtUsuarioApellido2 = new javax.swing.JTextField();
        lblUsuarioCorreo = new javax.swing.JLabel();
        txtUsuarioCorreo = new javax.swing.JTextField();
        lblUsuarioContrasena = new javax.swing.JLabel();
        txtContrasenaUpdate = new javax.swing.JPasswordField();
        lblUsuarioDepartamento = new javax.swing.JLabel();
        cbDepartamentoUsuario = new javax.swing.JComboBox<>();
        btnAgregarUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        lblBusquedaNombreActivo1 = new javax.swing.JLabel();
        txtBusquedaUsuario = new javax.swing.JTextField();
        txtNombreDeUsuario = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        cbRolUsuario = new javax.swing.JComboBox<>();
        btnBuscarUsuario = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblIncidentes = new javax.swing.JTable();
        lblTituloIncidente = new javax.swing.JLabel();
        txtTituloIncidente = new javax.swing.JTextField();
        lblDescripcionIncidente = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcionIncidente = new javax.swing.JTextArea();
        lblEstadoIncidente = new javax.swing.JLabel();
        cbEstadoIncidente = new javax.swing.JComboBox<>();
        lblPrioridadIncidente = new javax.swing.JLabel();
        cbPrioridadIncidente = new javax.swing.JComboBox<>();
        lblReportadoPor = new javax.swing.JLabel();
        txtReportadoPor = new javax.swing.JTextField();
        lblAsignadoA = new javax.swing.JLabel();
        txtActivoAfectado = new javax.swing.JTextField();
        lblReportadoPor2 = new javax.swing.JLabel();
        txtAsignadoA1 = new javax.swing.JTextField();
        lblFechaAperturaTitulo = new javax.swing.JLabel();
        lblFechaCierreTitulo = new javax.swing.JLabel();
        lblFechaAperturaVariable = new javax.swing.JLabel();
        lblFechaCierreVariable = new javax.swing.JLabel();
        btnAgregarIncidente = new javax.swing.JButton();
        btnActualizarIncidente = new javax.swing.JButton();
        btnEliminarIncidente = new javax.swing.JButton();
        btnReporteIncidentes = new javax.swing.JButton();
        lblBusquedaIncidente = new javax.swing.JLabel();
        txtBusquedaIncidente = new javax.swing.JTextField();
        btnBuscarIncidente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActivos = new javax.swing.JTable();
        lblNombreActivo = new javax.swing.JLabel();
        txtNombreActivo = new javax.swing.JTextField();
        lblIPActivo = new javax.swing.JLabel();
        txtIPActivo = new javax.swing.JTextField();
        lblOSActivo = new javax.swing.JLabel();
        lblUbicacionActivo = new javax.swing.JLabel();
        txtUbicacionActivo = new javax.swing.JTextField();
        cbDepartamento = new javax.swing.JComboBox<>();
        lblDepartamento = new javax.swing.JLabel();
        lblBusquedaNombreActivo = new javax.swing.JLabel();
        txtBusquedaNombreActivo = new javax.swing.JTextField();
        btnAgregarActivo = new javax.swing.JButton();
        btnReporteActivos = new javax.swing.JButton();
        btnModificarActivo = new javax.swing.JButton();
        lblDepartamentoTotalTitulo = new javax.swing.JLabel();
        lblDepartamentoTotalActivos = new javax.swing.JLabel();
        lblOSTitulo = new javax.swing.JLabel();
        cbOSActivo = new javax.swing.JComboBox<>();
        lblOSTotalActivos = new javax.swing.JLabel();
        btnEliminarActivo = new javax.swing.JButton();
        btnBuscarActivo = new javax.swing.JButton();
        lblEstadoActivo = new javax.swing.JLabel();
        cbEstadoActivo = new javax.swing.JComboBox<>();
        lblTipoDeActivo = new javax.swing.JLabel();
        cbTipoDeActivo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsuarios);

        lblNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("Nombre de usuario : ");

        lblUsuarioNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioNombre.setText("Nombre : ");

        lblUsuarioApellido1.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioApellido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioApellido1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioApellido1.setText("Primer Apellido : ");

        txtUsuarioApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioApellido1ActionPerformed(evt);
            }
        });

        lblUsuarioApellido2.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioApellido2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioApellido2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioApellido2.setText("Segundo Apellido : ");

        txtUsuarioApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioApellido2ActionPerformed(evt);
            }
        });

        lblUsuarioCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioCorreo.setText("Correo :");

        txtUsuarioCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioCorreoActionPerformed(evt);
            }
        });

        lblUsuarioContrasena.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioContrasena.setText("Contraseña :");

        lblUsuarioDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarioDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioDepartamento.setText("Departamento: ");

        cbDepartamentoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "RRHH", "Seguridad", "Desarrollo", "Contabilidad", "Managers" }));
        cbDepartamentoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartamentoUsuarioActionPerformed(evt);
            }
        });

        btnAgregarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarUsuario.setText("Agregar");

        btnActualizarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarUsuario.setText("Actualizar");

        btnEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarUsuario.setText("Eliminar");

        lblBusquedaNombreActivo1.setBackground(new java.awt.Color(255, 255, 255));
        lblBusquedaNombreActivo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBusquedaNombreActivo1.setForeground(new java.awt.Color(0, 0, 0));
        lblBusquedaNombreActivo1.setText("Buscar por nombre de usuario: ");

        txtBusquedaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaUsuarioActionPerformed(evt);
            }
        });

        lblRol.setBackground(new java.awt.Color(255, 255, 255));
        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(0, 0, 0));
        lblRol.setText("Puesto: ");

        cbRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "TECNICO", "ENDUSER", " " }));

        btnBuscarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarUsuario.setText("Buscar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblNombreUsuario))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(lblUsuarioNombre)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(txtNombreDeUsuario)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBusquedaNombreActivo1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusquedaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblUsuarioApellido1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUsuarioApellido1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblUsuarioCorreo)
                                                    .addComponent(lblUsuarioContrasena)
                                                    .addComponent(lblUsuarioDepartamento)
                                                    .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblRol))
                                                .addGap(27, 27, 27))
                                            .addComponent(lblUsuarioApellido2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(btnActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtUsuarioCorreo)
                                                    .addComponent(cbDepartamentoUsuario, 0, 223, Short.MAX_VALUE)
                                                    .addComponent(cbRolUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtContrasenaUpdate)
                                                    .addComponent(txtUsuarioApellido2))))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioNombre)
                    .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioApellido1))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioApellido2))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioCorreo)
                    .addComponent(txtUsuarioCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasenaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioContrasena))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDepartamentoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioDepartamento))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarUsuario)
                            .addComponent(btnActualizarUsuario))
                        .addGap(47, 47, 47)
                        .addComponent(txtBusquedaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBusquedaNombreActivo1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarUsuario)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Usuarios", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        tblIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblIncidentes);

        lblTituloIncidente.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloIncidente.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloIncidente.setText("Titulo del Incidente : ");

        txtTituloIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloIncidenteActionPerformed(evt);
            }
        });

        lblDescripcionIncidente.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcionIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionIncidente.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcionIncidente.setText("Descripcion del incidente:");

        txtDescripcionIncidente.setColumns(20);
        txtDescripcionIncidente.setRows(5);
        jScrollPane4.setViewportView(txtDescripcionIncidente);

        lblEstadoIncidente.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoIncidente.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoIncidente.setText("Estado del incidente: ");

        cbEstadoIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABIERTO", "EN_PROCESO", "RESUELTO", "CANCELADO" }));

        lblPrioridadIncidente.setBackground(new java.awt.Color(255, 255, 255));
        lblPrioridadIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrioridadIncidente.setForeground(new java.awt.Color(0, 0, 0));
        lblPrioridadIncidente.setText("Prioridad:");

        cbPrioridadIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJA", "MEDIA", "ALTA", "CRITICA" }));

        lblReportadoPor.setBackground(new java.awt.Color(255, 255, 255));
        lblReportadoPor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReportadoPor.setForeground(new java.awt.Color(0, 0, 0));
        lblReportadoPor.setText("Reportado por:");

        lblAsignadoA.setBackground(new java.awt.Color(255, 255, 255));
        lblAsignadoA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAsignadoA.setForeground(new java.awt.Color(0, 0, 0));
        lblAsignadoA.setText("Asignado a: ");

        lblReportadoPor2.setBackground(new java.awt.Color(255, 255, 255));
        lblReportadoPor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReportadoPor2.setForeground(new java.awt.Color(0, 0, 0));
        lblReportadoPor2.setText("Activo impactado: ");

        lblFechaAperturaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaAperturaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaAperturaTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaAperturaTitulo.setText("Fecha Apertura: ");

        lblFechaCierreTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaCierreTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaCierreTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCierreTitulo.setText("Fecha Cierre: ");

        lblFechaAperturaVariable.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaAperturaVariable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaAperturaVariable.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaAperturaVariable.setText("<FechaApertura> ");

        lblFechaCierreVariable.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaCierreVariable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaCierreVariable.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCierreVariable.setText("<FechaCierre> ");

        btnAgregarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarIncidente.setText("Agregar");

        btnActualizarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarIncidente.setText("Actualizar");

        btnEliminarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarIncidente.setText("Eliminar");

        btnReporteIncidentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteIncidentes.setText("Reporte");

        lblBusquedaIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBusquedaIncidente.setForeground(new java.awt.Color(0, 0, 0));
        lblBusquedaIncidente.setText("Buscar incidente por ID: ");

        btnBuscarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarIncidente.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReportadoPor)
                                    .addComponent(lblAsignadoA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAsignadoA1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txtReportadoPor))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstadoIncidente)
                                    .addComponent(lblPrioridadIncidente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPrioridadIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEstadoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEliminarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblFechaAperturaTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFechaAperturaVariable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(lblFechaCierreTitulo))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblTituloIncidente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTituloIncidente)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaCierreVariable))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lblDescripcionIncidente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(lblReportadoPor2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtActivoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(985, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnAgregarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(btnActualizarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnReporteIncidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(lblBusquedaIncidente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBusquedaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloIncidente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaAperturaTitulo)
                    .addComponent(lblFechaCierreTitulo)
                    .addComponent(lblFechaAperturaVariable)
                    .addComponent(lblFechaCierreVariable))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReportadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReportadoPor)
                    .addComponent(lblEstadoIncidente)
                    .addComponent(cbEstadoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrioridadIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrioridadIncidente)
                    .addComponent(lblAsignadoA)
                    .addComponent(txtAsignadoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReportadoPor2)
                    .addComponent(txtActivoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDescripcionIncidente)))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarIncidente)
                    .addComponent(btnActualizarIncidente))
                .addGap(44, 44, 44)
                .addComponent(btnReporteIncidentes)
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusquedaIncidente)
                    .addComponent(txtBusquedaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnBuscarIncidente)
                .addGap(147, 147, 147)
                .addComponent(btnEliminarIncidente)
                .addGap(166, 166, 166))
            .addComponent(jScrollPane5)
        );

        jTabbedPane1.addTab("Incidentes", jPanel4);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        tblActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblActivos);

        lblNombreActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreActivo.setText("Nombre del activo : ");

        lblIPActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblIPActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIPActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblIPActivo.setText("Direccion IP :");

        lblOSActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblOSActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOSActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblOSActivo.setText("Sistema Operativo :");

        lblUbicacionActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblUbicacionActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUbicacionActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacionActivo.setText("Ubicacion del activo :");

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "RRHH", "Seguridad", "Desarrollo", "Contabilidad" }));

        lblDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        lblDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamento.setText("Departamento :");

        lblBusquedaNombreActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblBusquedaNombreActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBusquedaNombreActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblBusquedaNombreActivo.setText("Buscar por nombre del activo: ");

        btnAgregarActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarActivo.setText("Agregar");

        btnReporteActivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteActivos.setText("Reporte");

        btnModificarActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarActivo.setText("Modificar");

        lblDepartamentoTotalTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblDepartamentoTotalTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDepartamentoTotalTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamentoTotalTitulo.setText("Departamento: ");

        lblDepartamentoTotalActivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDepartamentoTotalActivos.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamentoTotalActivos.setText("0");

        lblOSTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblOSTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOSTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblOSTitulo.setText(" Sistema Operativo : ");

        cbOSActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows", "Mac", "Red Hat", "Ubuntu" }));

        lblOSTotalActivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOSTotalActivos.setForeground(new java.awt.Color(0, 0, 0));
        lblOSTotalActivos.setText("0");

        btnEliminarActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarActivo.setText("Eliminar Activo");

        btnBuscarActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarActivo.setText("Buscar");

        lblEstadoActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblEstadoActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblEstadoActivo.setText("Estado del Activo:  ");

        cbEstadoActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERATIVO", "CUARENTENA", "MANTENIMIENTO", "APAGADO" }));

        lblTipoDeActivo.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoDeActivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoDeActivo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoDeActivo.setText("Tipo de Activo");

        cbTipoDeActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HARDWARE", "SOFTWARE", "LICENCIA", "RED", "PERIFERICO", "OTRO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblOSTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblBusquedaNombreActivo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDepartamentoTotalActivos)
                                                .addComponent(txtBusquedaNombreActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblOSTotalActivos)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnReporteActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblOSActivo)
                                            .addGap(24, 24, 24)
                                            .addComponent(cbOSActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblNombreActivo)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNombreActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblIPActivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtIPActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnModificarActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(lblUbicacionActivo))
                                                .addComponent(lblDepartamento)
                                                .addComponent(lblEstadoActivo)
                                                .addComponent(lblTipoDeActivo))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbEstadoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtUbicacionActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbTipoDeActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblDepartamentoTotalTitulo)))
                        .addGap(0, 249, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActivo)
                    .addComponent(txtNombreActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPActivo)
                    .addComponent(txtIPActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOSActivo)
                    .addComponent(cbOSActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbicacionActivo)
                    .addComponent(txtUbicacionActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoActivo))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDeActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDeActivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarActivo)
                    .addComponent(btnModificarActivo))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusquedaNombreActivo)
                    .addComponent(txtBusquedaNombreActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnBuscarActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamentoTotalTitulo)
                    .addComponent(lblDepartamentoTotalActivos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOSTotalActivos)
                    .addComponent(lblOSTitulo))
                .addGap(18, 18, 18)
                .addComponent(btnReporteActivos)
                .addGap(13, 13, 13)
                .addComponent(btnEliminarActivo)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Activos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getTituloIncidente(){
        return txtTituloIncidente.getText().trim();
    }

    public JButton getBtnBuscarIncidente() {
        return btnBuscarIncidente;
    }
    
    
    
    public String getActivoBusqueda() {
        return txtBusquedaNombreActivo.getText().trim();
    }

    public EstadoActivo getEstadoDeActivo() {
        return EstadoActivo.valueOf(cbEstadoActivo.getSelectedItem().toString().toUpperCase());
    }

    public JButton getBtnBuscarActivo() {
        return btnBuscarActivo;
    }

    public void setBtnBuscarActivo(JButton btnBuscarActivo) {
        this.btnBuscarActivo = btnBuscarActivo;
    }

    public JComboBox<String> getCbEstadoActivo() {
        return cbEstadoActivo;
    }

    public void setCbEstadoActivo(JComboBox<String> cbEstadoActivo) {
        this.cbEstadoActivo = cbEstadoActivo;
    }

    public JComboBox<String> getCbTipoDeActivo() {
        return cbTipoDeActivo;
    }

    public void setCbTipoDeActivo(JComboBox<String> cbTipoDeActivo) {
        this.cbTipoDeActivo = cbTipoDeActivo;
    }

    public JLabel getLblEstadoActivo() {
        return lblEstadoActivo;
    }

    public void setLblEstadoActivo(JLabel lblEstadoActivo) {
        this.lblEstadoActivo = lblEstadoActivo;
    }

    public JLabel getLblTipoDeActivo() {
        return lblTipoDeActivo;
    }

    public void setLblTipoDeActivo(JLabel lblTipoDeActivo) {
        this.lblTipoDeActivo = lblTipoDeActivo;
    }

    public TipoActivo getTipoActivo() {
        return TipoActivo.valueOf(cbTipoDeActivo.getSelectedItem().toString().toUpperCase());
    }

    public String getNombreActivo() {
        return txtNombreActivo.getText().trim();
    }

    public String getIPActivo() {
        return txtIPActivo.getText().trim();
    }

    public String getOSActivo() {
        return String.valueOf(cbOSActivo.getSelectedItem().toString());
    }

    public String getUbicacionActivo() {
        return txtUbicacionActivo.getText().trim();
    }

    public String getDepartamentoActivo() {
        return String.valueOf(cbDepartamento.getSelectedItem().toString());
    }

    public String getNombre() {
        return txtUsuarioNombre.getText().trim();
    }

    public String getApellido1() {
        return txtUsuarioApellido1.getText().trim();
    }

    public String getApellido2() {
        return txtUsuarioApellido2.getText().trim();
    }

    public String getUsuario() {
        return txtNombreDeUsuario.getText().trim();
    }

    public String getPass() {
        return String.valueOf(txtContrasenaUpdate.getPassword());
    }

    public String getCorreo() {
        return txtUsuarioCorreo.getText().trim();
    }

    public String getDepartamento() {
        return String.valueOf(cbDepartamentoUsuario.getSelectedItem().toString());
    }

    public Rol getRol() {
        return Rol.valueOf(cbRolUsuario.getSelectedItem().toString().toUpperCase());
    }

    public String getUsuarioBusqueda() {
        return txtBusquedaUsuario.getText();
    }

    public JButton getBtnActualizarIncidente() {
        return btnActualizarIncidente;
    }

    public void setBtnActualizarIncidente(JButton btnActualizarIncidente) {
        this.btnActualizarIncidente = btnActualizarIncidente;
    }

    public JButton getBtnActualizarUsuario() {
        return btnActualizarUsuario;
    }

    public void setBtnActualizarUsuario(JButton btnActualizarUsuario) {
        this.btnActualizarUsuario = btnActualizarUsuario;
    }

    public JButton getBtnAgregarActivo() {
        return btnAgregarActivo;
    }

    public void setBtnAgregarActivo(JButton btnAgregarActivo) {
        this.btnAgregarActivo = btnAgregarActivo;
    }

    public JButton getBtnAgregarIncidente() {
        return btnAgregarIncidente;
    }

    public void setBtnAgregarIncidente(JButton btnAgregarIncidente) {
        this.btnAgregarIncidente = btnAgregarIncidente;
    }

    public JButton getBtnAgregarUsuario() {
        return btnAgregarUsuario;
    }

    public void setBtnAgregarUsuario(JButton btnAgregarUsuario) {
        this.btnAgregarUsuario = btnAgregarUsuario;
    }

    public JButton getBtnEliminarActivo() {
        return btnEliminarActivo;
    }

    public void setBtnEliminarActivo(JButton btnEliminarActivo) {
        this.btnEliminarActivo = btnEliminarActivo;
    }

    public JButton getBtnEliminarIncidente() {
        return btnEliminarIncidente;
    }

    public JButton getBtnBuscarUsuario() {
        return btnBuscarUsuario;
    }

    public void setBtnBuscarUsuario(JButton btnBuscarUsuario) {
        this.btnBuscarUsuario = btnBuscarUsuario;
    }

    public void setBtnEliminarIncidente(JButton btnEliminarIncidente) {
        this.btnEliminarIncidente = btnEliminarIncidente;
    }

    public JButton getBtnEliminarUsuario() {
        return btnEliminarUsuario;
    }

    public void setBtnEliminarUsuario(JButton btnEliminarUsuario) {
        this.btnEliminarUsuario = btnEliminarUsuario;
    }

    public JButton getBtnModificarActivo() {
        return btnModificarActivo;
    }

    public void setBtnModificarActivo(JButton btnModificarActivo) {
        this.btnModificarActivo = btnModificarActivo;
    }

    public JButton getBtnReporteIncidentes() {
        return btnReporteIncidentes;
    }

    public void setBtnReporte(JButton btnReporte) {
        this.btnReporteIncidentes = btnReporte;
    }

    public JButton getBtnReporteActivos() {
        return btnReporteActivos;
    }

    public void setBtnReporteActivos(JButton btnReporteActivos) {
        this.btnReporteActivos = btnReporteActivos;
    }

    public JComboBox<String> getCbDepartamento() {
        return cbDepartamento;
    }

    public void setCbDepartamento(JComboBox<String> cbDepartamento) {
        this.cbDepartamento = cbDepartamento;
    }

    public JComboBox<String> getCbDepartamentoUsuario() {
        return cbDepartamentoUsuario;
    }

    public void setCbDepartamentoUsuario(JComboBox<String> cbDepartamentoUsuario) {
        this.cbDepartamentoUsuario = cbDepartamentoUsuario;
    }

    public JComboBox<String> getCbEstadoIncidente() {
        return cbEstadoIncidente;
    }

    public void setCbEstadoIncidente(JComboBox<String> cbEstadoIncidente) {
        this.cbEstadoIncidente = cbEstadoIncidente;
    }

    public JComboBox<String> getCbOSActivo() {
        return cbOSActivo;
    }

    public void setCbOSActivo(JComboBox<String> cbOSActivo) {
        this.cbOSActivo = cbOSActivo;
    }

    public JComboBox<String> getCbPrioridadIncidente() {
        return cbPrioridadIncidente;
    }

    public void setCbPrioridadIncidente(JComboBox<String> cbPrioridadIncidente) {
        this.cbPrioridadIncidente = cbPrioridadIncidente;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }


    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTextArea getDescripcionIncidente() {
        return txtDescripcionIncidente;
    }

    public void setDescripcionIncidente(JTextArea descripcionIncidente) {
        this.txtDescripcionIncidente = descripcionIncidente;
    }

    public JLabel getLblAsignadoA() {
        return lblAsignadoA;
    }

    public void setLblAsignadoA(JLabel lblAsignadoA) {
        this.lblAsignadoA = lblAsignadoA;
    }

    public JLabel getLblBusquedaNombreActivo() {
        return lblBusquedaNombreActivo;
    }

    public void setLblBusquedaNombreActivo(JLabel lblBusquedaNombreActivo) {
        this.lblBusquedaNombreActivo = lblBusquedaNombreActivo;
    }

    public JLabel getLblBusquedaNombreActivo1() {
        return lblBusquedaNombreActivo1;
    }

    public void setLblBusquedaNombreActivo1(JLabel lblBusquedaNombreActivo1) {
        this.lblBusquedaNombreActivo1 = lblBusquedaNombreActivo1;
    }

    public JLabel getLblDepartamento() {
        return lblDepartamento;
    }

    public void setLblDepartamento(JLabel lblDepartamento) {
        this.lblDepartamento = lblDepartamento;
    }

    public JLabel getLblDepartamentoTotalActivos() {
        return lblDepartamentoTotalActivos;
    }

    public void setLblDepartamentoTotalActivos(JLabel lblDepartamentoTotalActivos) {
        this.lblDepartamentoTotalActivos = lblDepartamentoTotalActivos;
    }

    public JLabel getLblDepartamentoTotalTitulo() {
        return lblDepartamentoTotalTitulo;
    }

    public void setLblDepartamentoTotalTitulo(JLabel lblDepartamentoTotalTitulo) {
        this.lblDepartamentoTotalTitulo = lblDepartamentoTotalTitulo;
    }

    public JLabel getLblDescripcionIncidente() {
        return lblDescripcionIncidente;
    }

    public void setLblDescripcionIncidente(JLabel lblDescripcionIncidente) {
        this.lblDescripcionIncidente = lblDescripcionIncidente;
    }

    public JLabel getLblEstadoIncidente() {
        return lblEstadoIncidente;
    }

    public void setLblEstadoIncidente(JLabel lblEstadoIncidente) {
        this.lblEstadoIncidente = lblEstadoIncidente;
    }

    public JLabel getLblFechaAperturaTitulo() {
        return lblFechaAperturaTitulo;
    }

    public void setLblFechaAperturaTitulo(JLabel lblFechaAperturaTitulo) {
        this.lblFechaAperturaTitulo = lblFechaAperturaTitulo;
    }

    public JLabel getLblFechaAperturaVariable() {
        return lblFechaAperturaVariable;
    }

    public void setLblFechaAperturaVariable(JLabel lblFechaAperturaVariable) {
        this.lblFechaAperturaVariable = lblFechaAperturaVariable;
    }

    public JLabel getLblFechaCierreTitulo() {
        return lblFechaCierreTitulo;
    }

    public void setLblFechaCierreTitulo(JLabel lblFechaCierreTitulo) {
        this.lblFechaCierreTitulo = lblFechaCierreTitulo;
    }

    public JLabel getLblFechaCierreVariable() {
        return lblFechaCierreVariable;
    }

    public void setLblFechaCierreVariable(JLabel lblFechaCierreVariable) {
        this.lblFechaCierreVariable = lblFechaCierreVariable;
    }

    public JLabel getLblIPActivo() {
        return lblIPActivo;
    }

    public void setLblIPActivo(JLabel lblIPActivo) {
        this.lblIPActivo = lblIPActivo;
    }

    public JLabel getLblNombreActivo() {
        return lblNombreActivo;
    }

    public void setLblNombreActivo(JLabel lblNombreActivo) {
        this.lblNombreActivo = lblNombreActivo;
    }

    public JLabel getLblNombreUsuario() {
        return lblNombreUsuario;
    }

    public void setLblNombreUsuario(JLabel lblNombreUsuario) {
        this.lblNombreUsuario = lblNombreUsuario;
    }

    public JLabel getLblOSActivo() {
        return lblOSActivo;
    }

    public void setLblOSActivo(JLabel lblOSActivo) {
        this.lblOSActivo = lblOSActivo;
    }

    public JLabel getLblOSTitulo() {
        return lblOSTitulo;
    }

    public void setLblOSTitulo(JLabel lblOSTitulo) {
        this.lblOSTitulo = lblOSTitulo;
    }

    public JLabel getLblOSTotalActivos() {
        return lblOSTotalActivos;
    }

    public void setLblOSTotalActivos(JLabel lblOSTotalActivos) {
        this.lblOSTotalActivos = lblOSTotalActivos;
    }

    public JLabel getLblPrioridadIncidente() {
        return lblPrioridadIncidente;
    }

    public void setLblPrioridadIncidente(JLabel lblPrioridadIncidente) {
        this.lblPrioridadIncidente = lblPrioridadIncidente;
    }

    public JLabel getLblReportadoPor() {
        return lblReportadoPor;
    }

    public void setLblReportadoPor(JLabel lblReportadoPor) {
        this.lblReportadoPor = lblReportadoPor;
    }

    public JLabel getLblReportadoPor2() {
        return lblReportadoPor2;
    }

    public void setLblReportadoPor2(JLabel lblReportadoPor2) {
        this.lblReportadoPor2 = lblReportadoPor2;
    }

    public JLabel getLblTituloIncidente() {
        return lblTituloIncidente;
    }

    public void setLblTituloIncidente(JLabel lblTituloIncidente) {
        this.lblTituloIncidente = lblTituloIncidente;
    }

    public JLabel getLblUbicacionActivo() {
        return lblUbicacionActivo;
    }

    public void setLblUbicacionActivo(JLabel lblUbicacionActivo) {
        this.lblUbicacionActivo = lblUbicacionActivo;
    }

    public JLabel getLblUsuarioApellido1() {
        return lblUsuarioApellido1;
    }

    public void setLblUsuarioApellido1(JLabel lblUsuarioApellido1) {
        this.lblUsuarioApellido1 = lblUsuarioApellido1;
    }

    public JLabel getLblUsuarioApellido2() {
        return lblUsuarioApellido2;
    }

    public void setLblUsuarioApellido2(JLabel lblUsuarioApellido2) {
        this.lblUsuarioApellido2 = lblUsuarioApellido2;
    }

    public JLabel getLblUsuarioContrasena() {
        return lblUsuarioContrasena;
    }

    public void setLblUsuarioContrasena(JLabel lblUsuarioContrasena) {
        this.lblUsuarioContrasena = lblUsuarioContrasena;
    }

    public JLabel getLblUsuarioCorreo() {
        return lblUsuarioCorreo;
    }

    public JTextArea getTxtDescripcionIncidente() {
        return txtDescripcionIncidente;
    }

    public void setTxtDescripcionIncidente(JTextArea txtDescripcionIncidente) {
        this.txtDescripcionIncidente = txtDescripcionIncidente;
    }

    public void setLblUsuarioCorreo(JLabel lblUsuarioCorreo) {
        this.lblUsuarioCorreo = lblUsuarioCorreo;
    }

    public JLabel getLblUsuarioDepartamento() {
        return lblUsuarioDepartamento;
    }

    public void setLblUsuarioDepartamento(JLabel lblUsuarioDepartamento) {
        this.lblUsuarioDepartamento = lblUsuarioDepartamento;
    }

    public JLabel getLblUsuarioNombre() {
        return lblUsuarioNombre;
    }

    public void setLblUsuarioNombre(JLabel lblUsuarioNombre) {
        this.lblUsuarioNombre = lblUsuarioNombre;
    }

    public JTable getTblActivos() {
        return tblActivos;
    }

    public void setTblActivos(JTable tblActivos) {
        this.tblActivos = tblActivos;
    }

    public JTable getTblIncidentes() {
        return tblIncidentes;
    }

    public void setTblIncidentes(JTable tblIncidentes) {
        this.tblIncidentes = tblIncidentes;
    }

    public JTable getTblUsuarios() {
        return tblUsuarios;
    }

    public void setTblUsuarios(JTable tblUsuarios) {
        this.tblUsuarios = tblUsuarios;
    }

    public JTextField getTxtActivoAfectado() {
        return txtActivoAfectado;
    }

    public void setTxtActivoAfectado(JTextField txtActivoAfectado) {
        this.txtActivoAfectado = txtActivoAfectado;
    }

    public JTextField getTxtAsignadoA1() {
        return txtAsignadoA1;
    }

    public void setTxtAsignadoA1(JTextField txtAsignadoA1) {
        this.txtAsignadoA1 = txtAsignadoA1;
    }

    public JTextField getTxtBusquedaNombreActivo() {
        return txtBusquedaNombreActivo;
    }

    public void setTxtBusquedaNombreActivo(JTextField txtBusquedaNombreActivo) {
        this.txtBusquedaNombreActivo = txtBusquedaNombreActivo;
    }

    public JTextField getTxtBusquedaUsuario() {
        return txtBusquedaUsuario;
    }

    public void setTxtBusquedaUsuario(JTextField txtBusquedaUsuario) {
        this.txtBusquedaUsuario = txtBusquedaUsuario;
    }

    public JPasswordField getTxtContrasenaUpdate() {
        return txtContrasenaUpdate;
    }

    public void setTxtContrasenaUpdate(JPasswordField txtContrasenaUpdate) {
        this.txtContrasenaUpdate = txtContrasenaUpdate;
    }

    public JTextField getTxtIPActivo() {
        return txtIPActivo;
    }

    public void setTxtIPActivo(JTextField txtIPActivo) {
        this.txtIPActivo = txtIPActivo;
    }

    public JTextField getTxtNombreActivo() {
        return txtNombreActivo;
    }

    public void setTxtNombreActivo(JTextField txtNombreActivo) {
        this.txtNombreActivo = txtNombreActivo;
    }

    public JTextField getTxtNombreDeUsuario() {
        return txtNombreDeUsuario;
    }

    public void setTxtNombreDeUsuario(JTextField txtNombreDeUsuario) {
        this.txtNombreDeUsuario = txtNombreDeUsuario;
    }

    public JTextField getTxtReportadoPor() {
        return txtReportadoPor;
    }

    public void setTxtReportadoPor(JTextField txtReportadoPor) {
        this.txtReportadoPor = txtReportadoPor;
    }

    public JTextField getTxtTituloIncidente() {
        return txtTituloIncidente;
    }

    public void setTxtTituloIncidente(JTextField txtTituloIncidente) {
        this.txtTituloIncidente = txtTituloIncidente;
    }

    public JTextField getTxtUbicacionActivo() {
        return txtUbicacionActivo;
    }

    public void setTxtUbicacionActivo(JTextField txtUbicacionActivo) {
        this.txtUbicacionActivo = txtUbicacionActivo;
    }

    public JTextField getTxtUsuarioApellido1() {
        return txtUsuarioApellido1;
    }

    public void setTxtUsuarioApellido1(JTextField txtUsuarioApellido1) {
        this.txtUsuarioApellido1 = txtUsuarioApellido1;
    }

    public JTextField getTxtUsuarioApellido2() {
        return txtUsuarioApellido2;
    }

    public void setTxtUsuarioApellido2(JTextField txtUsuarioApellido2) {
        this.txtUsuarioApellido2 = txtUsuarioApellido2;
    }

    public JTextField getTxtUsuarioCorreo() {
        return txtUsuarioCorreo;
    }

    public void setTxtUsuarioCorreo(JTextField txtUsuarioCorreo) {
        this.txtUsuarioCorreo = txtUsuarioCorreo;
    }

    public JTextField getTxtUsuarioNombre() {
        return txtUsuarioNombre;
    }

    public void setTxtUsuarioNombre(JTextField txtUsuarioNombre) {
        this.txtUsuarioNombre = txtUsuarioNombre;
    }

    public JComboBox<String> getCbRolUsuario() {
        return cbRolUsuario;
    }

    public void setCbRolUsuario(JComboBox<String> cbRolUsuario) {
        this.cbRolUsuario = cbRolUsuario;
    }

    public JLabel getLblRol() {
        return lblRol;
    }

    public void setLblRol(JLabel lblRol) {
        this.lblRol = lblRol;
    }


    private void txtUsuarioApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioApellido1ActionPerformed

    private void txtUsuarioApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioApellido2ActionPerformed

    private void txtUsuarioCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioCorreoActionPerformed

    private void txtBusquedaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaUsuarioActionPerformed

    private void cbDepartamentoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartamentoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartamentoUsuarioActionPerformed

    private void txtTituloIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloIncidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloIncidenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarIncidente;
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnAgregarActivo;
    private javax.swing.JButton btnAgregarIncidente;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBuscarActivo;
    private javax.swing.JButton btnBuscarIncidente;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEliminarActivo;
    private javax.swing.JButton btnEliminarIncidente;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnModificarActivo;
    private javax.swing.JButton btnReporteActivos;
    private javax.swing.JButton btnReporteIncidentes;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JComboBox<String> cbDepartamentoUsuario;
    private javax.swing.JComboBox<String> cbEstadoActivo;
    private javax.swing.JComboBox<String> cbEstadoIncidente;
    private javax.swing.JComboBox<String> cbOSActivo;
    private javax.swing.JComboBox<String> cbPrioridadIncidente;
    private javax.swing.JComboBox<String> cbRolUsuario;
    private javax.swing.JComboBox<String> cbTipoDeActivo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAsignadoA;
    private javax.swing.JLabel lblBusquedaIncidente;
    private javax.swing.JLabel lblBusquedaNombreActivo;
    private javax.swing.JLabel lblBusquedaNombreActivo1;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDepartamentoTotalActivos;
    private javax.swing.JLabel lblDepartamentoTotalTitulo;
    private javax.swing.JLabel lblDescripcionIncidente;
    private javax.swing.JLabel lblEstadoActivo;
    private javax.swing.JLabel lblEstadoIncidente;
    private javax.swing.JLabel lblFechaAperturaTitulo;
    private javax.swing.JLabel lblFechaAperturaVariable;
    private javax.swing.JLabel lblFechaCierreTitulo;
    private javax.swing.JLabel lblFechaCierreVariable;
    private javax.swing.JLabel lblIPActivo;
    private javax.swing.JLabel lblNombreActivo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblOSActivo;
    private javax.swing.JLabel lblOSTitulo;
    private javax.swing.JLabel lblOSTotalActivos;
    private javax.swing.JLabel lblPrioridadIncidente;
    private javax.swing.JLabel lblReportadoPor;
    private javax.swing.JLabel lblReportadoPor2;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTipoDeActivo;
    private javax.swing.JLabel lblTituloIncidente;
    private javax.swing.JLabel lblUbicacionActivo;
    private javax.swing.JLabel lblUsuarioApellido1;
    private javax.swing.JLabel lblUsuarioApellido2;
    private javax.swing.JLabel lblUsuarioContrasena;
    private javax.swing.JLabel lblUsuarioCorreo;
    private javax.swing.JLabel lblUsuarioDepartamento;
    private javax.swing.JLabel lblUsuarioNombre;
    private javax.swing.JTable tblActivos;
    private javax.swing.JTable tblIncidentes;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtActivoAfectado;
    private javax.swing.JTextField txtAsignadoA1;
    private javax.swing.JTextField txtBusquedaIncidente;
    private javax.swing.JTextField txtBusquedaNombreActivo;
    private javax.swing.JTextField txtBusquedaUsuario;
    private javax.swing.JPasswordField txtContrasenaUpdate;
    private javax.swing.JTextArea txtDescripcionIncidente;
    private javax.swing.JTextField txtIPActivo;
    private javax.swing.JTextField txtNombreActivo;
    private javax.swing.JTextField txtNombreDeUsuario;
    private javax.swing.JTextField txtReportadoPor;
    private javax.swing.JTextField txtTituloIncidente;
    private javax.swing.JTextField txtUbicacionActivo;
    private javax.swing.JTextField txtUsuarioApellido1;
    private javax.swing.JTextField txtUsuarioApellido2;
    private javax.swing.JTextField txtUsuarioCorreo;
    private javax.swing.JTextField txtUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
